# -*- coding: utf-8 -*-
"""Analisis_de_telemetria.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZhJBFreotkZd-IIScd5BJ8KvpxPipm-
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import io

def cargar_y_mostrar_csv():
    print("📤 SUBIR ARCHIVO CSV DE TELEMETRÍA")
    print("=" * 50)

    # Subir archivo
    uploaded = files.upload()

    if not uploaded:
        print("❌ No se subió ningún archivo")
        return None

    for filename in uploaded.keys():
        print(f'✅ Archivo subido: "{filename}"')

        # Leer el CSV
        try:
            if filename.endswith('.csv'):
                df = pd.read_csv(io.BytesIO(uploaded[filename]))
                print(f"📊 Datos cargados: {len(df)} filas x {len(df.columns)} columnas")
                return df
            else:
                print("❌ El archivo debe ser .csv")
                return None

        except Exception as e:
            print(f"❌ Error al leer el archivo: {e}")
            return None

def crear_graficas_completas(df):
    print("\n📈 CREANDO GRÁFICAS DE ANÁLISIS...")
    print("=" * 40)

    # Verificar qué columnas están disponibles
    columnas_disponibles = df.columns.tolist()
    print(f"🔍 Columnas disponibles: {columnas_disponibles}")

    # Configurar el estilo
    plt.style.use('default')
    sns.set_palette("husl")

    # Determinar cuántas gráficas crear basado en las columnas disponibles
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    fig.suptitle('ANÁLISIS COMPLETO DE TELEMETRÍA', fontsize=16, fontweight='bold')

    grafica_actual = 0

    # 1. Gráfica de Acelerómetro (si existe)
    if all(col in df.columns for col in ['acc_x', 'acc_y', 'acc_z']):
        row, col = divmod(grafica_actual, 3)
        axes[row, col].plot(df['acc_x'], label='X', alpha=0.8, linewidth=1.5)
        axes[row, col].plot(df['acc_y'], label='Y', alpha=0.8, linewidth=1.5)
        axes[row, col].plot(df['acc_z'], label='Z', alpha=0.8, linewidth=1.5)
        axes[row, col].set_title('Acelerómetro (m/s²)', fontweight='bold')
        axes[row, col].legend()
        axes[row, col].grid(True, alpha=0.3)
        axes[row, col].set_ylabel('Aceleración (m/s²)')
        grafica_actual += 1

    # 2. Gráfica de Giroscopio (si existe)
    if all(col in df.columns for col in ['gyro_x', 'gyro_y']):
        row, col = divmod(grafica_actual, 3)
        axes[row, col].plot(df['gyro_x'], label='X', alpha=0.8, linewidth=1.5, color='red')
        axes[row, col].plot(df['gyro_y'], label='Y', alpha=0.8, linewidth=1.5, color='blue')
        axes[row, col].set_title('Giroscopio (deg/s)', fontweight='bold')
        axes[row, col].legend()
        axes[row, col].grid(True, alpha=0.3)
        axes[row, col].set_ylabel('Velocidad Angular (deg/s)')
        grafica_actual += 1

    # 3. Gráfica de Temperatura (si existe)
    if 'temperatura' in df.columns:
        row, col = divmod(grafica_actual, 3)
        axes[row, col].plot(df['temperatura'], alpha=0.8, linewidth=2, color='orange')
        axes[row, col].set_title('Temperatura (°C)', fontweight='bold')
        axes[row, col].grid(True, alpha=0.3)
        axes[row, col].set_ylabel('Temperatura (°C)')
        grafica_actual += 1

    # 4. Gráfica de Batería (si existe)
    if 'bateria' in df.columns:
        row, col = divmod(grafica_actual, 3)
        axes[row, col].plot(df['bateria'], alpha=0.8, linewidth=2, color='green')
        axes[row, col].set_title('Voltaje Batería (V)', fontweight='bold')
        axes[row, col].grid(True, alpha=0.3)
        axes[row, col].set_ylabel('Voltaje (V)')
        grafica_actual += 1

    # 5. Gráfica de Velocidad (si existe)
    if 'velocidad' in df.columns:
        row, col = divmod(grafica_actual, 3)
        axes[row, col].plot(df['velocidad'], alpha=0.8, linewidth=2, color='purple')
        axes[row, col].set_title('Velocidad GPS (km/h)', fontweight='bold')
        axes[row, col].grid(True, alpha=0.3)
        axes[row, col].set_ylabel('Velocidad (km/h)')
        grafica_actual += 1

    # 6. Gráfica de PWM (si existe)
    if all(col in df.columns for col in ['servo_pwm', 'motor_pwm']):
        row, col = divmod(grafica_actual, 3)
        axes[row, col].plot(df['servo_pwm'], label='Servo', alpha=0.8, linewidth=1.5)
        axes[row, col].plot(df['motor_pwm'], label='Motor', alpha=0.8, linewidth=1.5)
        axes[row, col].set_title('Señales PWM (μs)', fontweight='bold')
        axes[row, col].legend()
        axes[row, col].grid(True, alpha=0.3)
        axes[row, col].set_ylabel('Ancho de Pulso (μs)')
        grafica_actual += 1

    # Ocultar ejes vacíos
    for i in range(grafica_actual, 6):
        row, col = divmod(i, 3)
        axes[row, col].set_visible(False)

    plt.tight_layout()
    plt.show()

    # Gráfica adicional: Mapa de calor de correlaciones
    if len(df.select_dtypes(include=['number']).columns) > 1:
        print("\n🔥 MAPA DE CORRELACIONES")
        plt.figure(figsize=(10, 8))
        numeric_df = df.select_dtypes(include=['number'])
        correlation_matrix = numeric_df.corr()

        sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0,
                   square=True, linewidths=0.5)
        plt.title('Mapa de Correlación entre Variables', fontweight='bold')
        plt.tight_layout()
        plt.show()

def mostrar_estadisticas(df):
    print("\n📊 ESTADÍSTICAS DESCRIPTIVAS")
    print("=" * 40)

    # Solo columnas numéricas
    numeric_columns = df.select_dtypes(include=['number']).columns

    for col in numeric_columns:
        if col in df.columns:
            print(f"\n📈 {col.upper()}:")
            stats = df[col].describe()
            print(f"   Count: {stats['count']:.0f}")
            print(f"   Mean:  {stats['mean']:.2f}")
            print(f"   Std:   {stats['std']:.2f}")
            print(f"   Min:   {stats['min']:.2f}")
            print(f"   Max:   {stats['max']:.2f}")

# PROGRAMA PRINCIPAL
print("🚀 ANALIZADOR DE TELEMETRÍA - CSV + GRÁFICAS")
print("=" * 55)

# Cargar datos
df = cargar_y_mostrar_csv()

if df is not None:
    # Mostrar información básica
    print(f"\n📋 INFORMACIÓN DEL DATASET:")
    print(f"   • Dimensiones: {df.shape[0]} filas x {df.shape[1]} columnas")
    print(f"   • Columnas: {list(df.columns)}")
    print(f"   • Tipos de datos:")
    print(df.dtypes)

    # Mostrar primeras filas
    print(f"\n👀 PRIMERAS 5 FILAS:")
    print(df.head())

    # Crear gráficas
    crear_graficas_completas(df)

    # Mostrar estadísticas
    mostrar_estadisticas(df)

    print("\n✅ ANÁLISIS COMPLETADO!")

else:
    print("❌ No se pudieron cargar los datos para análisis")